export const METERING_FIELD_LABELS: Record<string, string> = {
  list_number: 'Номер по списку',
  contract_number: 'Номер договора',
  name: 'Наименование',
  address: 'Адрес объекта',
  identifier: 'Идентификатор',
  input_kind: 'Первичный/повторный',
  date_input_uute: 'Дата ввода УУТЭ',
  admit_until: 'Допуск до',
  date_output_uute: 'Дата вывода УУТЭ',
  output_reason: 'Причина вывода',
  act_primary_number: 'Номер акта ввода',
  act_periodic_number: 'Номер акта проверки',
  registration_date: 'Дата регистрации',
  violations: 'Нарушения',
  verifier: 'Поверитель',
  documents: 'Документы',
  heat_load: 'Нагрузка отопление',
  hot_water_load: 'Нагрузка ГВС',
  ventilation_load: 'Нагрузка вентиляция',
  contract_flow: 'Договорной расход',
  distance: 'Расстояние',
  diameter: 'Диаметр',
  connection_point_number: 'Номер точки присоединения',
  installation_point: 'Точка установки УУТЭ',
  calculator_type: 'Тепловычислитель',
  calculator_serial: 'Тепловычислитель №',
  flowmeter_1: 'Расходомер 1',
  flowmeter_2: 'Расходомер 2',
  temp_sensor_1: 'Датчик температуры на ПС 1',
  temp_sensor_2: 'Датчик температуры на ПС 2',
  pressure_sensor_1: 'Датчик давления на ПС 1',
  pressure_sensor_2: 'Датчик давления на ПС 2',
  flowmeter_serial_1: 'Расходомер 1 №',
  flowmeter_serial_2: 'Расходомер 2 №',
  temp_sensor_serial_1: 'Датчик температуры на ПС 1 №',
  temp_sensor_serial_2: 'Датчик температуры на ПС 2 №',
  pressure_sensor_serial_1: 'Датчик давления на ПС 1 №',
  pressure_sensor_serial_2: 'Датчик давления на ПС 2 №',
  calculator_verification_date: 'Дата окончания поверки тепловычислителя',
  flowmeter_verification_date_1: 'Дата окончания поверки расходомера ПС',
  flowmeter_verification_date_2: 'Дата окончания поверки расходомера ОС',
  temp_sensor_verification_date_1: 'Дата окончания поверки датчика температуры на ПС',
  temp_sensor_verification_date_2: 'Дата окончания поверки датчика температуры на ОС',
  pressure_sensor_verification_date_1: 'Дата окончания поверки датчика давления на ПС',
  pressure_sensor_verification_date_2: 'Дата окончания поверки датчика давления на ОС',
  nearest_verification_date: 'Ближайшая поверка',
  seal_calculator: 'Пломба тепловычислителя №',
  seal_flowmeter_1: 'Пломба расходомера ПС №',
  seal_flowmeter_2: 'Пломба расходомера ОС №',
  seal_temp_sensor_1: 'Пломба датчика температуры на ПС 1 №',
  seal_temp_sensor_2: 'Пломба датчика температуры на ОС №',
  seal_cut_1: 'Пломба врезка №1',
  seal_cut_2: 'Пломба врезка №2',
  seal_cut_3: 'Пломба врезка №3',
  seal_cut_4: 'Пломба врезка №4',
  seals_checked: 'Пломбы сверены',
  system_type: 'Тип системы',
  service_org: 'Обслуживающая организация',
  readings_date: 'Дата показаний',
  reading_q: 'Q',
  reading_m1: 'M1',
  reading_v1: 'V1',
  reading_m2: 'M2',
  reading_v2: 'V2',
  reading_t1: 't1',
  reading_t2: 't2',
  reading_p1: 'P1',
  reading_p2: 'P2',
  accepted_by: 'Принимал',
  check_date: 'Дата проверки',
  check_violations: 'Нарушения проверки',
  check_note: 'Примечание проверки',
}

export function meteringFieldLabel(key: string): string {
  return METERING_FIELD_LABELS[key] || key
}
