export const METERING_FIELD_LABELS: Record<string, string> = {
  list_number: 'Номер по списку',
  contract_number: 'Номер договора',
  name: 'Наименование',
  address: 'Адрес объекта',
  identifier: 'Идентификатор',
  input_kind: 'Первичная / периодическая',
  date_input_uute: 'Дата ввода УУТЭ',
  admit_until: 'Допущен до',
  date_output_uute: 'Дата вывода УУТЭ',
  output_reason: 'Причина вывода',
  act_primary_number: 'Номер акта ввода',
  act_periodic_number: 'Номер акта периодической проверки',
  registration_date: 'Дата регистрации',
  violations: 'Нарушения',
  verifier: 'Поверитель',
  documents: 'Документы',
  heat_load: 'Тепловая нагрузка',
  hot_water_load: 'Нагрузка ГВС',
  ventilation_load: 'Нагрузка вентиляции',
  contract_flow: 'Договорный расход',
  distance: 'Расстояние',
  diameter: 'Диаметр',
  connection_point_number: 'Номер точки подключения',
  installation_point: 'Место установки УУТЭ',
  calculator_type: 'Тепловычислитель',
  calculator_serial: 'Заводской номер тепловычислителя',
  flowmeter_1: 'Расходомер 1',
  flowmeter_2: 'Расходомер 2',
  flowmeter_3: 'Расходомер 3',
  flowmeter_4: 'Расходомер 4',
  temp_sensor_1: 'Датчик температуры 1 (подача)',
  temp_sensor_2: 'Датчик температуры 2 (обратка)',
  temp_sensor_3: 'Датчик температуры 3',
  temp_sensor_4: 'Датчик температуры 4',
  pressure_sensor_1: 'Датчик давления 1 (подача)',
  pressure_sensor_2: 'Датчик давления 2 (обратка)',
  pressure_sensor_3: 'Датчик давления 3',
  pressure_sensor_4: 'Датчик давления 4',
  flowmeter_serial_1: 'Заводской номер расходомера 1',
  flowmeter_serial_2: 'Заводской номер расходомера 2',
  flowmeter_serial_3: 'Заводской номер расходомера 3',
  flowmeter_serial_4: 'Заводской номер расходомера 4',
  temp_sensor_serial_1: 'Заводской номер датчика температуры 1',
  temp_sensor_serial_2: 'Заводской номер датчика температуры 2',
  temp_sensor_serial_3: 'Заводской номер датчика температуры 3',
  temp_sensor_serial_4: 'Заводской номер датчика температуры 4',
  pressure_sensor_serial_1: 'Заводской номер датчика давления 1',
  pressure_sensor_serial_2: 'Заводской номер датчика давления 2',
  pressure_sensor_serial_3: 'Заводской номер датчика давления 3',
  pressure_sensor_serial_4: 'Заводской номер датчика давления 4',
  calculator_verification_date: 'Срок поверки тепловычислителя',
  flowmeter_verification_date_1: 'Срок поверки расходомера 1',
  flowmeter_verification_date_2: 'Срок поверки расходомера 2',
  flowmeter_verification_date_3: 'Срок поверки расходомера 3',
  flowmeter_verification_date_4: 'Срок поверки расходомера 4',
  temp_sensor_verification_date_1: 'Срок поверки датчика температуры 1',
  temp_sensor_verification_date_2: 'Срок поверки датчика температуры 2',
  temp_sensor_verification_date_3: 'Срок поверки датчика температуры 3',
  temp_sensor_verification_date_4: 'Срок поверки датчика температуры 4',
  pressure_sensor_verification_date_1: 'Срок поверки датчика давления 1',
  pressure_sensor_verification_date_2: 'Срок поверки датчика давления 2',
  pressure_sensor_verification_date_3: 'Срок поверки датчика давления 3',
  pressure_sensor_verification_date_4: 'Срок поверки датчика давления 4',
  nearest_verification_date: 'Ближайшая дата поверки',
  seal_calculator: 'Номер пломбы тепловычислителя',
  seal_flowmeter_1: 'Номер пломбы расходомера 1',
  seal_flowmeter_2: 'Номер пломбы расходомера 2',
  seal_temp_sensor_1: 'Номер пломбы датчика температуры 1',
  seal_temp_sensor_2: 'Номер пломбы датчика температуры 2',
  seal_cut_1: 'Пломба врезки №1',
  seal_cut_2: 'Пломба врезки №2',
  seal_cut_3: 'Пломба врезки №3',
  seal_cut_4: 'Пломба врезки №4',
  seals_checked: 'Пломбы проверены',
  system_type: 'Тип системы',
  service_org: 'Обслуживающая организация',
  readings_date: 'Дата показаний',
  reading_q: 'Q',
  reading_m1: 'M1',
  reading_v1: 'V1',
  reading_m2: 'M2',
  reading_v2: 'V2',
  reading_t1: 't1',
  reading_t2: 't2',
  reading_p1: 'P1',
  reading_p2: 'P2',
  accepted_by: 'Принято',
  check_date: 'Дата проверки',
  check_violations: 'Нарушения при проверке',
  check_note: 'Примечание при проверке',
}

export function meteringFieldLabel(key: string): string {
  return METERING_FIELD_LABELS[key] || key
}
